### ISSUE TITLE
No option for passing credentials to ELK

### ISSUE THREAD

**Issue by rts-dev** [defenxor/dsiem#196]
Am I missing something from the docs explaining how to pass credentials to Elasticsearch, Logstash, and Kibana? 

Even tried setting `DSIEM_WEB_ESURL` to http://user:password@elasticsearch:9200 but the web ui still says `Disconnected from ES http://user:password@elasticsearch:9200`.

**Comment by mmta** [comment]
Setting `DSIEM_WEB_ESURL` in the way you described is the correct way to pass basic auth information to Elasticsearch. Try the following steps to investigate further:

- Make sure there's no network issue between your computer and ES by first opening 'http://user:password@elasticsearch:9200' directly from the browser.

- If the above works but Dsiem web UI still fails, check if there's CORS related error in the browser developer tools console (for Chrome it's from `More tools` -> `Developer tools` -> `Console`). If there is, then you'll need to adjust ES CORS setting to allow access. Specifically, while troubleshooting try to change the following:

https://github.com/defenxor/dsiem/blob/7059c2405db9d1261c6e035cfda499c52815aed5/deployments/docker/docker-compose.yml#L16-L17

to:
```
 - http.cors.enabled=true 
 - http.cors.allow-origin=*
```
Then restart ES before trying again.

For Kibana, I'm not sure we can pass basic auth info through URL like in ES case above. As a workaround, you can just manually login to Kibana from a separate browser tab, before clicking any Kibana link in Dsiem.

**Comment by mmta** [comment]
> I hadn't realized the variables were being used by javascript. I thought dsiem itself was needing to interact with the stack

Good point, we should document this behaviour somewhere.

We intentionally avoid interfacing dsiem (the command) directly with Elastic components because we want it to be usable with other stack if needed. Currently dsiem just receives (normalized) logs from Logstash through http, and writes output as json files to be harvested by Filebeat. So you see, its possible to replace Logstash + Filebeat with something from, say, the Fluentd project, without having to modify dsiem command.

> I'm not a fan of it displaying the password on the web UI, however.

lol yeah, apparently this is something that we overlook. @Cempakers87 should have a fix for this sometime next week.

You should also be aware though, the way dsiem command pass those URL information to the web UI, is by writing them to `http://[dsiem-ip]:8080/ui/assets/config/esconfig.json`. So merely hiding the ES basic auth info from the web output won't be enough to protect them: you will also need to restrict access to esconfig.json.

This hasn't been a problem in our own deployments because we put Dsiem web UI and the rest of `/ui/` behind an Nginx frontend that encrypts and authenticates all access to it. And also we haven't used the web UI directly against an ES security-enabled cluster yet.

> Maybe adjust the javascript to trim that part or simply display a connection success/fail icon? Or adding variables to insert username:password into the headers rather than passing them in the URL?

For sure we shouldn't display those sensitive info on the screen.

But for now I'm not sure if we should replace `esconfig.json` method above with something else. Authentication and secure handling of any credential is something that I'd rather delegate to the infrastructure (like nginx) or other reputable framework than implementing it in dsiem web UI.

So maybe we'll end up just hiding those info from the screen, and providing an extra warning regarding `esconfig.json` if it contains basic auth credentials.

Anyway, thanks for this very useful feedback 👍
