### ISSUE TITLE
DSIEM WEB UI Support login verification?

### ISSUE THREAD

**Issue by Canon88** [defenxor/dsiem#246]
Hi, DSIEM Team:
     We will deploy DSIEM in production. Now does the DSIEM WEB UI support login validation? Or will it be later?

**Comment by mmta** [comment]
Hi @Canon88, Dsiem web UI doesn't implement user authentication because it is just a client-side javascript app that accesses your Elasticsearch directly. So the things you can access from the web UI, you can also access them using any other web client. 

Now if you're concerned about restricting access, the thing to protect should be your ES endpoint (port 9200), Kibana, and the esconfig.json file (if it contains sensitive authentication info).

If you still need to restrict access to Dsiem web UI for some reason though, then I'd recommend to use nginx or haproxy with TLS and some form of user authentication as a frontend to it. Here's one example project that can do that:  https://github.com/jwilder/nginx-proxy.

**Comment by Canon88** [comment]
thx!
