### ISSUE TITLE
Disconnected from ES http://localhost:9200: Error: No Living connections

### ISSUE THREAD

**Issue by Lorental** [defenxor/dsiem#266]
Hi guys!
I tried to install DSIEM and connect it to existing ELK installation. After all steps in manual I have an error like this. Interesting thing that I have have this error with localhost:9200, but my friend has it with elastic.local what we are using as domain name for elastic server.
I also has an icmp connection between nodes and both nodes are in one network without any acl, elastic is accessable by ip by remote kibana and logstash.

**Comment by ebeahan** [comment]
I ran into the same problem. The DSIEM webui needs to be configured with the hostname/IP of Elasticsearch that your browser will need to resolve. I stumbled across [this comment](https://github.com/defenxor/dsiem/issues/246#issuecomment-554491856) which made me realize my issue.

In my case I had to replace `http://localhost:9200` for `DSIEM_WEB_ESURL` in my `docker-compose.yml` configuration with an IP address my browser could use to connect to Elasticsearch (vs `localhost`):

replaced:

```
    environment:
      - DSIEM_WEB_ESURL=http://localhost:9200
      - DSIEM_WEB_KBNURL=http://localhost:5601
```

with:

```
    environment:
      - DSIEM_WEB_ESURL=http://<ipAddress>:9200
      - DSIEM_WEB_KBNURL=http://<ipAddress>:5601
```

**Comment by A00279521** [comment]
I know this issue was closed but I have tried 
     {
         "elasticsearch":  "http://localhost:9200"
          "kibana":  "http://localhost:5601"
      }

and I also tried 
{
        "elasticsearch":  "http://<ipAddress of my vm>:9200"
          "kibana":  "http://l<ipAddress of my vm:5601"

}

But the result is the same. That is  "Disconnected from ES http://localhost:9200: Error: No Living connections" and  
" Disconnected from ES http://<ipAddress of my vm>:9200: Error: No Living connections"
AM running this on Ubuntu 20.4 VM. The ELK is working fine and I have Suricata also installed with the suricata-* logs and siem_events-* visible in my kibana. I have followed the instructions in the installation.md in github
